# Example https://github.com/nais/naiserator/blob/master/examples/nais-max.yaml
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-kafka-offset-monitor
  namespace: default
  labels:
    team: teamdagpenger
  annotations:
    zone: fss
spec:
  image: repo.adeo.no:5443/dp-kafka-offset-monitor:latest
  port: 8080
  team: teamdagpenger
  liveness:
    path: isAlive
  readiness:
    path: isReady
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 256Mi
  prometheus:
    enabled: true
    path: /metrics
  vault:  
    enabled: true
  env:
    - name: PROMETHEUS_NAMESPACE
      value: dp
    - name: CONSUMER_GROUPS
      value: dagpenger-joark-mottak,dagpenger-inntekt-datasamler,dagpenger-regel-minsteinntekt,dagpenger-regel-periode,dagpenger-regel-sats,dagpenger-regel-grunnlag,dp-regel-api,srvdp-vedtakresultat-lytter,dp-regel-api-sub-brukt,dp-inntekt-api-consumer
